name: GHA Handy Workflow Reference

on:
  push:
    branches:    
      - '**'

  workflow_dispatch:
    inputs:
      note:
        description: 'Describe why you are doing this'
        required: false
        default: 'no message' 


jobs:
  just-macos-things:
    runs-on: macos-latest
    steps:
      - name: some basic items
        run: |
          printf "github.event_name:                  %s\n"   ${{ github.event_name }}
          printf "runner.os:                          %s\n"   ${{ runner.os }}
          printf "github.ref (branch):                %s\n"   ${{ github.ref }}
          printf "github.repository:                  %s\n"   ${{ github.repository }}

  ubuntu-town:
    runs-on: ubuntu-latest
    steps:
      - name: some basic items
        run: |
          printf "github.event_name:                  %s\n"   ${{ github.event_name }}
          printf "runner.os:                          %s\n"   ${{ runner.os }}
          printf "github.ref (branch):                %s\n"   ${{ github.ref }}
          printf "github.repository:                  %s\n"   ${{ github.repository }}
          printf "job (job_id):                       %s\n"   ${{ job }}
          printf "job.status:                         %s\n"   ${{ job.status }}

      - name: ubuntu shell environment situation
        run: |
          echo "sed --version"
          sed --version
          echo "which sed"
          which sed
          echo "awk --version"
          awk --version
          echo "env"
          env

      - name: Release branch and tag extraction
        run: |
          echo "release_name=release--/v.0.2.0"
          release_name='release--/v.0.2.0'
          echo "sed --posix  's/.*release.*([0-9].[0-9].[0-9])/v\1/'"
          release_tag_name=$(echo "$release_name" \
            | sed --posix  's/.*release.*([0-9].[0-9].[0-9])/v\1/')
          printf "release_tag_name:                 %s\n"   $release_tag_name

      - name: Are shell variables persistent between steps?
        run: |
          printf "release_name"                     %s\n"   $release_name
          printf "release_tag_name:                 %s\n"   $release_tag_name


  official-actions-usage:
    runs-on: ubuntu-latest
    steps:
      - name: actions/checkout@v3 - pull down repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: General environment and context items
        run: |
          printf "github.repository:                        %s\n"   ${{ github.repository }}
          printf "github.event.workflow_run.head_branch:    %s\n"   ${{ github.event.workflow_run.head_branch }}

          echo   "$> ls github.workspace"
          ls ${{ github.workspace }}

      - name: Configure for autobot commits
        run: |
          git config user.name gha-bot
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git config --list

      - name: checkout@v3 repo stuff and git operations
        run: |
          echo "Does the config remain between steps?"
          echo "git config --list"
          git config --list
          echo "git branch --list"
          git branch --list
          echo "git checkout github.event.workflow_run.head_branch: ${{ github.event.workflow_run.head_branch }}"
          git checkout "${{ github.event.workflow_run.head_branch }}"
          echo "git log  --graph -n20 --pretty=format:'%h %as %cn %x09%s %d'"
          git log  --graph -n20 --pretty=format:'%h %as %cn %x09%s %d'


      - name: actions/github-script@v6 - View context attributes
        uses: actions/github-script@v6
        with:
          script: console.log(context)
