name: Merge Release Branch and Tag

env:
  ACTIONS_STEP_DEBUG: true

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  tag-release:
    runs-on: ubuntu-latest
    if: |
      github.event.pull_request.merged == true &&
      startsWith(github.event.pull_request.head.ref, 'release/')
    steps:
      - name: Show PR info
        run: |
          echo "PR merged from: ${{ github.event.pull_request.head.ref }}"
          echo "PR merged to: ${{ github.event.pull_request.base.ref }}"

      - name: Checkout the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate tag name
        id: tag
        run: |
          release_branch="${{ github.event.pull_request.head.ref }}"
          tag_name=$(echo "$release_branch" | sed -E 's/.*release.*([0-9]+\.[0-9]+\.[0-9]+).*/v\1/')
          echo "release_tag_name=$tag_name" >> $GITHUB_OUTPUT
          echo "Generated tag: $tag_name"

      - name: Create and push tag
        run: |
          git config user.name gha-bot
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git tag --annotate "${{ steps.tag.outputs.release_tag_name }}" -m "release ${{ steps.tag.outputs.release_tag_name }}"
          git push origin "${{ steps.tag.outputs.release_tag_name }}"
          echo
          echo "++++++++++++++++++++++++++++++++++++++++++++++++++++"
          git log --graph --all -n10 --pretty=format:'%h %as %cn %x09%s %d'
          echo "Tag "${{ steps.tag.outputs.release_tag_name }}" created and pushed"
          echo "YOU CAN DELETE RELEASE BRANCH: $RELEASE_BRANCH"
