name: Merge to Main After Tests

on:
  workflow_run:
    workflows: [Test desertislandutils]
    types: [completed]
    branches:
      - 'release/**'

jobs:
  print-context:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: echo 'The triggering workflow passed'
      - run: |
          echo "now i have to merge release into main somehow"
          git branch
          git log  --graph -n20 --pretty=format:'%C(bold red)%h%Creset %C(cyan)%as%Creset %C(green)%cn%Creset %x09%C(white)%s%Creset %C(yellow)%d%Creset'
          git config --list

  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'STOP THE PRESSES NO MERGE. MUST SEND A MESSAGE'
