name: Merge to Main After Tests

on:
  workflow_run:
    workflows: [Test desertislandutils]
    types: [completed]
    branches:
      - 'release/**'

  # this allows manual trigger from UI
  workflow_dispatch:
    inputs:
      note:
        description: 'Describe why you are doing this'
        required: false
        default: 'no message' 

jobs:
  print-vars:
    runs-on: ubuntu-latest
    steps:
      - name: Show workspace contexts
        run: |
          echo "workspace: ${{ github.workspace }}"
          echo "head branch of trigger run: ${{ github.event.workflow_run.head_branch }}"
          echo "ls ${{ github.workspace }}"
          ls ${{ github.workspace }}

      - name: Are variables persistent between steps
        run: |
          echo "which sed is avail on ubuntu:"
          sed --version
          which sed
          echo "release_branch_name=  github.event.workflow_run.head_branch "
          release_tag_name=$(echo ""release/ --v.0.2.0"" \
            | sed --posix  's/.*release.*([0-9].[0-9].[0-9])/v\1/')

      - name: Merge the latest release
        run: |
          echo "release_tag_name: $release_tag_name"

  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: 'Merge release workflow triggered by tests passing'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Show workspace contexts
        run: |
          echo "workspace: ${{ github.workspace }}"
          echo "head branch of trigger run: ${{ github.event.workflow_run.head_branch }}"
          echo "ls ${{ github.workspace }}"
          ls ${{ github.workspace }}

      - name: Do I really have all the branches
        run: |
          git config user.name GHA
          git config user.email github-actions@github.com
          git config --list
          git branch --list
          git checkout "${{ github.event.workflow_run.head_branch }}"
          git log  --graph -n20 --pretty=format:'%h %as %cn %x09%s %d'
          echo "which sed is avail on ubuntu:"
          sed --version
          which sed
      - name: Are variables persistent between steps
        run: |
          echo "release_branch_name=  github.event.workflow_run.head_branch "
          release_tag_name=$(echo "${{ github.event.workflow_run.head_branch }}" \
            | sed --posix  's/.*release.*([0-9].[0-9].[0-9])/v\1/')

      - name: Merge the latest release
        run: |
          echo "release_tag_name: $release_tag_name"
      #   run: |
      #     echo "doing: git merge --no-ff ${{ github.event.workflow_run.head_branch }}"
      #     echo "context of release branch: ${{ github.event.workflow_run.head_branch }}"
      #     git checkout main
      #     git merge --no-ff "${{ github.event.workflow_run.head_branch }}"
      #     git checkout main
      #     git tag -a v0.2.0 -m "release $release_tag_name"
      #     git log  --graph -n20 --pretty=format:'%h %as %cn %x09%s %d'
      #     echo 'running: git push --tags'
      #     git push --tags
      # - run: |
      #     git checkout dev
      #     git merge --no-ff main
      #     git push --tags
      #     echo "merged main back to dev - carry on development from here"
      #     echo "you can delete your release branch now"

      - name: Show context attributes
        uses: actions/github-script@v6
        with:
          script: console.log(context)


# TODO: pull tag name from the version of pyproject.toml, or strip from release

  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'STOP THE PRESSES NO MERGE. MUST SEND A MESSAGE'
