name: Merge to Main After Tests

on:
  workflow_run:
    workflows: [Test desertislandutils]
    types: [completed]
    branches:
      - 'release/**'

  # this allows manual trigger from UI
  workflow_dispatch:
    inputs:
      note:
        description: 'Describe why you are doing this'
        required: false
        default: 'no message' 

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: 'Merge release workflow triggered by tests passing'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Show workspace contexts
        run: |
          echo "workspace: ${{ github.workspace }}"
          echo "head branch of trigger run: ${{ github.event.workflow_run.head_branch }}"
          echo "ls ${{ github.workspace }}"
          ls ${{ github.workspace }}

      - name: Do I really have all the branches
        run: |
          git config user.name GHA
          git config user.email github-actions@github.com
          git config --list
          git branch --list
          git checkout release/0.2.0
          git log  --graph -n20 --pretty=format:'%C(bold red)%h%Creset %C(cyan)%as%Creset %C(green)%cn%Creset %x09%C(white)%s%Creset %C(yellow)%d%Creset'

      - name: Merge the latest release
        run: |
          echo "doing: git merge --no-ff release/x.x.x"
          echo "context of release branch: ${{ github.event.workflow_run.head_branch }}"
          git checkout main
          git merge --no-ff release/0.2.0
      - run: |
          git tag -a v0.2.0 -m 'release v0.2.0'
          git log  --graph -n20 --pretty=format:'%C(bold red)%h%Creset %C(cyan)%as%Creset %C(green)%cn%Creset %x09%C(white)%s%Creset %C(yellow)%d%Creset'
          git push --tags
      - run: |
          git checkout dev
          git merge --no-ff release/0.2.0
          git push

      - name: Show context attributes
        uses: actions/github-script@v6
        with:
          script: console.log(context)


# TODO: pull name of triggering branch from context github.event.workflow_run.head_branch
# TODO: pull tag name from the version of pyproject.toml, or strip from release

  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'STOP THE PRESSES NO MERGE. MUST SEND A MESSAGE'
