name: Merge to Main After Tests

on:
  workflow_run:
    workflows: [Test desertislandutils]
    types: [completed]
    branches:
      - 'release/**'

  # this allows manual trigger from UI
  workflow_dispatch:
    inputs:
      note:
        description: 'Describe why you are doing this'
        required: false
        default: 'no message' 

jobs:
  print-context:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          # ref: main
      - run: |
          echo "printing workflow git situation"
          git branch --list
          git log  --graph -n20 --pretty=format:'%C(bold red)%h%Creset %C(cyan)%as%Creset %C(green)%cn%Creset %x09%C(white)%s%Creset %C(yellow)%d%Creset'
          git config --list
      - name: Show context attributes
        uses: actions/github-script@v6
        with:
          script: console.log(context)

          
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: echo 'The triggering workflow passed'
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - run: |
          echo "${{ github.workspace }}"
          ls ${{ github.workspace }}

      - name: Do I really have all the branches
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git config --list
          git branch --list
          git checkout release/0.2.0
          git log  --graph -n20 --pretty=format:'%C(bold red)%h%Creset %C(cyan)%as%Creset %C(green)%cn%Creset %x09%C(white)%s%Creset %C(yellow)%d%Creset'

      - name: Merge the latest release
        run: |
          echo "doing: git merge --no-ff release/x.x.x"
          git checkout main
          git merge --no-ff release/0.2.0
      - run: |  
          git tag -a v0.2.0
          git log  --graph -n20 --pretty=format:'%C(bold red)%h%Creset %C(cyan)%as%Creset %C(green)%cn%Creset %x09%C(white)%s%Creset %C(yellow)%d%Creset'
      - run: |
          git checkout dev
          git merge --no-ff release/0.2.0
          git push

# TODO: pull name of triggering branch from context github.event.workflow_run.head_branch
# TODO: pull tag name from the version of pyproject.toml, or strip from release

  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'STOP THE PRESSES NO MERGE. MUST SEND A MESSAGE'
