name: Test desertislandutils

on:
  push:
    branches:
      - 'release/**'
    paths-ignore:
      - '**.md'

  workflow_dispatch:
    inputs:
      note:
        description: 'Describe why you are doing this'
        required: false
        default: 'no message' 

jobs:
  poetry-run-tests:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - run: python --version

      - name: Install poetry with pipx and python version
        run: pipx install --python $(which python) poetry
      - run: poetry install
      - run: poetry run pytest

      - name: Print some workflow contexts
        run: |
          echo "workflow: ${{ github.workflow }}"
          echo "job_id:  ${{ github.job }}"
          echo "job status:  ${{ job.status }}"
