name: Test desertislandutils

env:
  ACTIONS_STEP_DEBUG: true

concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - '**'
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [main]
    paths-ignore: ['**.md']

  # NOTE: workflow_dispatch only work on main
  workflow_dispatch:
    inputs:
      note:
        description: 'Describe why you are doing this'
        required: false
        default: 'no message'
      manual_workflow_conclusion:
        description: 'Insert success/failure for downstream'
        required: false
        default: ''
        type: choice
        options:
        - ' '
        - failure
        - success

jobs:
  uv-run-tests:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install UV
        uses: astral-sh/setup-uv@v5

      - name: UV Sync and Test
        run: |
          python --version
          uv --version
          uv sync --all-extras
          uv run pytest --disable-warnings --verbose
          echo "WARNING: Pytest Warnings are disabled"

      - name: Get Latest Tag
        id: get_tag
        run: |
          latest_tag="$(git ls-remote origin 'refs/tags/v*[0-9]' | awk -F'refs/tags/' '{print $2}' | sort -V | tail -1)"
          echo latest_tag="${latest_tag}" >> $GITHUB_OUTPUT

      - name: Get desertislandutils Version
        id: app_version
        run: |
          app_version="$(uv version | awk '{print $2}')"
          echo app_version="v${app_version}" >> $GITHUB_OUTPUT

      - name: REFERENCE - Variables and Workflow Contexts
        run: |
          echo "workflow: ${{ github.workflow }}"
          echo "job_id:  ${{ github.job }}"
          echo "job status:  ${{ job.status }}"
          echo "commit ref name:  ${{ github.ref_name }}"
          echo "branch name: ${{ github.ref }}"
          echo "latest tag: ${{ steps.get_tag.outputs.latest_tag }}"
          echo "app version: ${{ steps.app_version.outputs.app_version }}"
